[workspace]
members = [
    # Temporarily removed because it isn't going to cleanly build for a while.
    "build",
    "desc",
    "tasks",
    "ninja",
    "parse",
]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
