[package]
name = "ninja"
version = "0.1.0"
authors = ["Nikhil Marathe <nsm.nikhil@gmail.com>"]
edition = "2018"

[dependencies]
ninja-parse = { path = "../parse" }
# ninja-build = { path = "../build" }
ninja-interface = { path = "../interface" }
ninja-desc = { path = "../desc" }

# Temporary for the model.
petgraph = "^0.5"
