[package]
name = "ninja"
version = "0.1.0"
authors = ["Nikhil Marathe <nsm.nikhil@gmail.com>"]
edition = "2018"

[dependencies]
ninja-parse = { path = "../parse" }
ninja-build = { path = "../build" }
ninja-desc = { path = "../desc" }
ninja-tasks = { path = "../tasks" }
anyhow = "^1.0"

# Temporary for the model.
petgraph = "^0.5"
