[package]
name = "ninja-interface"
version = "0.1.0"
authors = ["Nikhil Marathe <nsm.nikhil@gmail.com>"]
edition = "2018"

[dependencies]
# TODO: Possible to wrap behind generics/traits
ninja-tasks = { path = "../tasks" }
