[package]
name = "ninja-metrics"
version = "0.1.0"
authors = ["Nikhil Marathe <nsm.nikhil@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "^1.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

